# Constants
BASEURL = '../db/'
CLASSIFICATION = 'classification.csv'
EXHIBIT = 'exhibit.csv'
HABITAT = 'habitat.csv'
REGION = 'region.csv'
SPECIES = 'species.csv'
STATE = 'state.csv'
STATUS = 'status.csv'
ZOO = 'zoo.csv'
